permalink: pretty

plugins:
  - jekyll-remote-theme

remote_theme: dhilanr/jekyll-theme-crestlex

url: https://tinyml.seas.harvard.edu
baseurl: /SciTinyML-24

title: SciTinyML 2024

alert:
    - success